version: "3"
services:
  app:
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    ports:
      - 8080:80
      - 444:444
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network

  phpma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8085:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
